---
title: "Conference presentations"
description: "Presentations from the Seeding Success project"
---

### 2015

Falster K, Jorm L, Eades S, Lynch J, Banks E, Brownell M, Craven R, Einarsdottir K, Randall D, on behalf the Seeding Success investigators. **The Seeding Success study: protocol for a population-based cohort study using linked administrative data.** The Australian Early Development Census conference, Adelaide, Australia, February 2015. (Oral symposium presentation).

### 2016

Falster K, Hanly M, Jorgensen K, Jorm L. **The Seeding Success Study: Identifying factors that contribute to positive early childhood health and development in Aboriginal children.** 14th Australian Institute of Family Studies Conference: Research to Results: Using evidence to improve outcomes for families, Melbourne, Australia, July 2016. (Oral presentation)

Hanly M, Falster K, Chambers G, Lynch J, Banks E, Homaira N, Brownell M, Eades S, Jorm L. **Gestational age and child development at age five in a population-based cohort of 97,989 Australian Aboriginal and non- Aboriginal children.** International Population Data Linkage Conference, August 2016, Swansea, Wales. (Oral presentation).

Hanly M, Falster K, Craven R and Jorm L. **School starting age and child development in a state-wide, population-level cohort of children in their first year of school in NSW, Australia.** International Population Data Linkage Conference, August 2016, Swansea, Wales. (Oral presentation).

Falster K, Hanly M, Banks E, Lynch J, Chambers G, Brownell M, Eades S, Jorm L. **Maternal age and offspring development at age five: a contemporary, population-based cohort study of 78,697 Australian children.** International Population Data Linkage Conference, August 2016, Swansea, Wales. (Rapid fire presentation, presented by M Hanly on behalf of K Falster).

Falster K, Hanly M, Banks E, Lynch J, Brownell M, Eades S, Jorm L. **Maternal age at childbirth and development outcomes at age five in Aboriginal and non-Aboriginal children: a population data linkage study.** Australasian Epidemiological Association (AEA) 23rd Annual Scientific Meeting, Canberra, Australia, September 2016. (oral presentation).

### 2017

Falster K, Hanly M, Banks E, Lynch J, Brownell M, Eades S, Jorm L. **Maternal age at childbirth and development outcomes at age five: a population data linkage study.** Australasian Epidemiological Association (AEA) 24th Annual Scientific Meeting, Sydney, Australia, September 2017. (Oral presentation).

### 2018
Falster K, Hanly M, Pilkington R, Chilvers M, Whittaker E, Lynch J. **Developmental vulnerability at age five among children who enter and progress through the child protection system in New South Wales, Australia: a cross-sectoral data linkage study.** International Population Data Linkage Conference, September 2018, Banff, Canada. (Oral presentation).

### 2020 
Gibberd A, Tyler J, Preen D, Falster K, Hanly M, Clarke M, McNamara B, Eades S, Scurrah K.
**Outcomes of Indigenous Twin and Singleton Pregnancies: Complications, Medical Care, Birth Experience and Infant Health** International Population Data Linkage Conference, November 2020. (Virtual oral presentation)